server:
  port: 8002
mybatis:
  # 指定全局配置文件位置
    config-location: classpath:mybatis/mybatis-config.xml
    # 指定sql映射文件位置
    mapper-locations: classpath:mybatis/mapper/**/*.xml
    type-aliases-package: com.jiangfan.springcloud.entity
spring:
   application:
    name: microserviceprovider-dept            #这个名称会被注册到eureka
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02              # 数据库名称
    username: root
    password: jiangfan
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200  # 等待连接获取的最大超时时间
eureka:
  client:  #客户端注册eureka服务列表
    service-url:
      #defaultZone:  http://localhost:7001/eureka
      defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:           #自定义注册到eureka server的服务名
    instance-id:  microServicePrividerDept-8002
     #访问路径可以设置为IP地址,也就是访问eureka的web界面时在status一栏，鼠标放到服务名上去会显示生产者的Ip地址+端口
    prefer-ip-address: true
#status链接的信息
info:
  app.name:  jianfan-springcloud01
  company.name: com.jiangfan
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"