server:
  port: 7001
eureka:
  instance:
     #hostname: localhost
    hostname: eureka7001.com  #eureka 服务端实例名
  client:
    register-with-eureka: false #false表示不向注册中心注册自己这个服务
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护实例，并不需要检索服务
    service-url:
        #设置与eureka server 交互地址注册和查询服务都需要依赖这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
       defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/